export const S = {
  root: { minHeight: "100vh", background: "#f1f5f9", color: "#0f172a", fontFamily: "'Noto Sans TC', 'Microsoft JhengHei', sans-serif" },
  toast: { position: "fixed", top: 16, left: "50%", transform: "translateX(-50%)", padding: "10px 24px", borderRadius: 24, color: "#fff", fontWeight: 700, fontSize: 15, zIndex: 999, boxShadow: "0 4px 20px #0003", whiteSpace: "nowrap" },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 20px", background: "#fff", borderBottom: "2px solid #e2e8f0", boxShadow: "0 1px 4px #0001" },
  headerLeft: { display: "flex", alignItems: "center", gap: 12 },
  logo: { fontSize: 34, lineHeight: 1 },
  title: { fontSize: 20, fontWeight: 800, color: "#0891b2" },
  subtitle: { fontSize: 12, color: "#94a3b8", letterSpacing: 2, textTransform: "uppercase" },
  headerRight: { display: "flex", alignItems: "center", gap: 8 },
  savingTxt: { fontSize: 13, color: "#0891b2", fontWeight: 600 },
  userInfo: { display: "flex", alignItems: "center", gap: 6 },
  userName: { fontWeight: 700, fontSize: 14, color: "#1e293b" },
  adminBadge: { fontSize: 10, padding: "1px 6px", borderRadius: 6, background: "#fef3c7", color: "#92400e", fontWeight: 700, border: "1px solid #fde68a" },
  userBtn: { display: "flex", alignItems: "center", gap: 6, background: "#f0f9ff", border: "1.5px solid #bae6fd", color: "#0369a1", padding: "7px 14px", borderRadius: 20, fontSize: 14, cursor: "pointer", fontWeight: 600 },
  adminLoginBtn: { display: "flex", alignItems: "center", gap: 4, background: "#fef3c7", border: "1.5px solid #fde68a", color: "#92400e", padding: "7px 14px", borderRadius: 20, fontSize: 13, cursor: "pointer", fontWeight: 700 },
  logoutBtn: { padding: "6px 14px", background: "#f1f5f9", border: "1.5px solid #e2e8f0", color: "#64748b", borderRadius: 20, fontSize: 13, cursor: "pointer", fontWeight: 600 },
  dot: { borderRadius: "50%", display: "inline-block", flexShrink: 0, width: 10, height: 10 },
  nav: { display: "flex", gap: 4, padding: "10px 16px", background: "#fff", borderBottom: "1px solid #e2e8f0" },
  navBtn: { padding: "8px 18px", borderRadius: 20, border: "1.5px solid transparent", background: "transparent", color: "#64748b", cursor: "pointer", fontSize: 14, fontWeight: 600 },
  navActive: { background: "#e0f2fe", color: "#0891b2", borderColor: "#bae6fd" },
  monthNav: { display: "flex", alignItems: "center", gap: 8, padding: "10px 14px", background: "#fff", borderBottom: "1px solid #e2e8f0", flexWrap: "wrap" },
  arrowBtn: { width: 34, height: 34, borderRadius: "50%", border: "1.5px solid #e2e8f0", background: "#f8fafc", color: "#475569", cursor: "pointer", fontSize: 20, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  monthLabel: { fontWeight: 800, fontSize: 17, color: "#1e293b", minWidth: 130, textAlign: "center" },
  genBtn: { marginLeft: "auto", padding: "8px 16px", background: "#0891b2", color: "#fff", border: "none", borderRadius: 20, fontWeight: 700, cursor: "pointer", fontSize: 14, boxShadow: "0 2px 8px #0891b230" },
  editToggleBtn: { padding: "8px 16px", background: "#fff", color: "#92400e", border: "1.5px solid #fcd34d", borderRadius: 20, fontWeight: 700, cursor: "pointer", fontSize: 14 },
  editToggleBtnActive: { background: "#fef3c7", color: "#92400e", borderColor: "#f59e0b", boxShadow: "0 2px 8px #f59e0b30" },
  clearBtn: { padding: "8px 14px", background: "#fff", color: "#dc2626", border: "1.5px solid #fca5a5", borderRadius: 20, fontWeight: 700, cursor: "pointer", fontSize: 14 },
  regenBtn: { padding: "8px 14px", background: "#fff", color: "#7c3aed", border: "1.5px solid #c4b5fd", borderRadius: 20, fontWeight: 700, cursor: "pointer", fontSize: 14 },
  docFillBtn: { padding: "8px 14px", background: "#fff", color: "#16a34a", border: "1.5px solid #86efac", borderRadius: 20, fontWeight: 700, cursor: "pointer", fontSize: 14 },
  reloadBtn: { width: 34, height: 34, borderRadius: "50%", border: "1.5px solid #e2e8f0", background: "#f8fafc", color: "#94a3b8", cursor: "pointer", fontSize: 17, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  loadingBar: { height: 3, background: "#e0f2fe", overflow: "hidden" },
  loadingFill: { height: "100%", width: "60%", background: "#0891b2" },
  editBanner: { background: "#fffbeb", borderBottom: "1px solid #fcd34d", padding: "8px 16px", fontSize: 13, color: "#92400e", fontWeight: 600 },
  content: { padding: "8px 10px 48px" },
  calGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 3, marginBottom: 3 },
  dowHeader: { textAlign: "center", fontSize: 13, padding: "6px 0", fontWeight: 700 },
  emptyCell: { minHeight: 80 },
  cell: { background: "#fff", borderRadius: 8, padding: "7px 6px", minHeight: 80, cursor: "pointer", border: "1.5px solid #e2e8f0", transition: "border-color 0.15s, box-shadow 0.15s", position: "relative", overflow: "hidden", boxShadow: "0 1px 2px #0001" },
  cellWG: { background: "#eff6ff", borderColor: "#bfdbfe" },
  cellFri: { background: "#fffbeb", borderColor: "#fde68a" },
  cellHoliday: { background: "#fff1f2", borderColor: "#fecdd3" },
  cellToday: { borderColor: "#0891b2", boxShadow: "0 0 0 2px #0891b230" },
  cellSelected: { borderColor: "#0891b2", background: "#e0f2fe" },
  cellEditMode: { cursor: "default", borderColor: "#fcd34d" },
  cellDay: { fontSize: 15, fontWeight: 800, lineHeight: 1.2 },
  cellDow: { fontSize: 10, color: "#94a3b8", marginBottom: 2 },
  lockIcon: { fontSize: 10, lineHeight: 1 },
  holidayLabel: { fontSize: 10, color: "#dc2626", fontWeight: 700, background: "#ffe4e6", borderRadius: 4, padding: "1px 4px", display: "inline-block", marginBottom: 2 },
  cellMembers: { display: "flex", flexWrap: "wrap", gap: 3 },
  chip: { fontSize: 11, padding: "2px 7px", borderRadius: 8, fontWeight: 600, lineHeight: 1.5, display: "inline-flex", alignItems: "center", gap: 2 },
  chipEditable: { cursor: "pointer", outline: "none" },
  chipRemove: { fontSize: 9, opacity: 0.7 },
  chipAdd: { fontSize: 10, padding: "2px 6px", borderRadius: 8, fontWeight: 600, background: "#f0fdf4", color: "#16a34a", border: "1.5px dashed #86efac", cursor: "pointer", lineHeight: 1.5 },
  leaveHint: { position: "absolute", top: 4, right: 4, fontSize: 10, color: "#dc2626", fontWeight: 700 },
  panel: { marginTop: 10, background: "#fff", border: "1.5px solid #bae6fd", borderRadius: 12, padding: "14px 16px", boxShadow: "0 2px 12px #0891b210" },
  panelHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  panelTitle: { fontWeight: 800, fontSize: 16, color: "#0891b2", display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  panelBadgeWG: { fontSize: 12, background: "#eff6ff", color: "#2563eb", padding: "2px 8px", borderRadius: 10, fontWeight: 600 },
  panelBadgeLock: { fontSize: 12, background: "#fef3c7", color: "#92400e", padding: "2px 8px", borderRadius: 10, fontWeight: 600 },
  panelBadgeHol: { fontSize: 12, background: "#fff1f2", color: "#dc2626", padding: "2px 8px", borderRadius: 10, fontWeight: 600 },
  panelClose: { width: 28, height: 28, borderRadius: "50%", border: "1.5px solid #e2e8f0", background: "#f8fafc", color: "#94a3b8", cursor: "pointer", fontSize: 14, display: "flex", alignItems: "center", justifyContent: "center" },
  panelLabel: { fontSize: 13, color: "#64748b", marginBottom: 10, fontWeight: 600 },
  oncallList: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 4 },
  oncallCard: { display: "flex", alignItems: "center", justifyContent: "space-between", background: "#f8fafc", borderRadius: 10, padding: "10px 14px", borderLeft: "4px solid #e2e8f0", gap: 10 },
  oncallCardLeft: { display: "flex", alignItems: "center", gap: 8, flex: 1 },
  phoneBtn: { display: "inline-flex", alignItems: "center", gap: 4, padding: "7px 14px", borderRadius: 20, border: "1.5px solid", background: "#fff", fontWeight: 700, fontSize: 14, textDecoration: "none", flexShrink: 0, whiteSpace: "nowrap" },
  memberRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  memberToggle: { padding: "8px 14px", borderRadius: 20, border: "1.5px solid #e2e8f0", background: "#f8fafc", color: "#334155", cursor: "pointer", fontSize: 13, fontWeight: 600, transition: "all 0.15s", display: "flex", alignItems: "center", gap: 5 },
  memberOnLeave: { opacity: 0.3, cursor: "not-allowed" },
  leaveNote: { fontSize: 14, color: "#475569", padding: "10px 4px 6px", fontWeight: 500 },
  statsGrid: { paddingTop: 12, display: "flex", flexDirection: "column", gap: 10 },
  statCard: { background: "#fff", borderRadius: 10, padding: "14px 18px", position: "relative", overflow: "hidden", display: "flex", alignItems: "center", border: "1.5px solid #e2e8f0", boxShadow: "0 1px 3px #0001" },
  statBar: { position: "absolute", left: 0, top: 0, bottom: 0, transition: "width 0.5s" },
  statInfo: { display: "flex", alignItems: "center", gap: 8, flex: 1, position: "relative", flexWrap: "wrap" },
  statName: { fontWeight: 700, fontSize: 15, color: "#0f172a" },
  statCount: { fontWeight: 800, fontSize: 18, position: "relative" },
  statsNote: { textAlign: "center", fontSize: 13, color: "#94a3b8", marginTop: 16 },
  roleTag: { fontSize: 11, padding: "2px 7px", borderRadius: 6, fontWeight: 600, display: "inline-block" },
  modalOverlay: { position: "fixed", inset: 0, background: "#00000066", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center" },
  modalBox: { background: "#fff", borderRadius: 16, padding: 24, border: "1px solid #e2e8f0", minWidth: 300, maxWidth: "90vw", boxShadow: "0 8px 32px #0002" },
  modalTitle: { fontWeight: 800, fontSize: 18, marginBottom: 16, color: "#0891b2" },
  modalGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  modalClose: { width: 28, height: 28, borderRadius: "50%", border: "1.5px solid #e2e8f0", background: "#f8fafc", color: "#94a3b8", cursor: "pointer", fontSize: 14, display: "flex", alignItems: "center", justifyContent: "center" },
  memberPickBtn: { padding: "10px 12px", borderRadius: 10, background: "#f8fafc", color: "#1e293b", border: "1.5px solid #e2e8f0", cursor: "pointer", display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", transition: "background 0.15s" },
  pickName: { fontWeight: 700, fontSize: 14, flex: 1 },
  authInput: { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1.5px solid #cbd5e1", fontSize: 15, outline: "none", boxSizing: "border-box" },
  authError: { fontSize: 13, color: "#dc2626", background: "#fee2e2", border: "1px solid #fca5a5", borderRadius: 8, padding: "8px 12px" },
  authHint: { fontSize: 13, color: "#92400e", background: "#fffbeb", border: "1px solid #fde68a", borderRadius: 8, padding: "8px 12px", marginBottom: 12 },
  authSwitchBtn: { background: "none", border: "none", color: "#0891b2", cursor: "pointer", fontSize: 13, textDecoration: "underline", textAlign: "center" },
  adminTabs: { display: "flex", gap: 4, marginBottom: 16, flexWrap: "wrap" },
  adminTabBtn: { padding: "8px 18px", borderRadius: 20, border: "1.5px solid #e2e8f0", background: "#f8fafc", color: "#64748b", cursor: "pointer", fontSize: 14, fontWeight: 600 },
  adminTabActive: { background: "#e0f2fe", color: "#0891b2", borderColor: "#bae6fd" },
  adminSection: { background: "#fff", borderRadius: 12, padding: 16, border: "1.5px solid #e2e8f0" },
  sectionTitle: { fontWeight: 800, fontSize: 16, color: "#1e293b", marginBottom: 12 },
  memberCard: { background: "#f8fafc", borderRadius: 10, padding: "12px 14px", border: "1.5px solid #e2e8f0", marginBottom: 8 },
  formBox: { background: "#f1f5f9", borderRadius: 10, padding: 14, border: "1.5px solid #e2e8f0", marginBottom: 12 },
  formRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8 },
  formLabel: { fontSize: 13, fontWeight: 600, color: "#475569", minWidth: 44 },
  formInput: { flex: 1, padding: "7px 10px", borderRadius: 8, border: "1.5px solid #cbd5e1", fontSize: 14, background: "#fff", color: "#1e293b", outline: "none" },
  formSelect: { flex: 1, padding: "7px 10px", borderRadius: 8, border: "1.5px solid #cbd5e1", fontSize: 14, background: "#fff", color: "#1e293b", outline: "none" },
  ruleSection: { borderBottom: "1px solid #e2e8f0", marginBottom: 14, paddingBottom: 14 },
  ruleSectionTitle: { fontWeight: 700, fontSize: 14, color: "#0891b2", marginBottom: 10 },
  ruleRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 },
  ruleLabel: { fontSize: 13, color: "#475569", minWidth: 120 },
  ruleValue: { fontWeight: 700, fontSize: 15, color: "#1e293b" },
  ruleUnit: { fontSize: 13, color: "#64748b", whiteSpace: "nowrap" },
  btnPrimary: { padding: "8px 16px", background: "#0891b2", color: "#fff", border: "none", borderRadius: 20, fontWeight: 700, cursor: "pointer", fontSize: 13 },
  btnSecondary: { padding: "8px 16px", background: "#f1f5f9", color: "#475569", border: "1.5px solid #e2e8f0", borderRadius: 20, fontWeight: 600, cursor: "pointer", fontSize: 13 },
  btnSmall: { padding: "5px 12px", background: "#f8fafc", color: "#334155", border: "1.5px solid #e2e8f0", borderRadius: 16, fontWeight: 600, cursor: "pointer", fontSize: 12 },
};
